# Generated by Django 5.1.6 on 2025-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_diet_options_diet_is_active_diet_is_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='plan',
        ),
        migrations.AddField(
            model_name='diet',
            name='diet',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
