# Generated by Django 5.1.6 on 2025-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_remove_diet_plan_diet_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
