# Generated by Django 5.1.6 on 2025-04-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_alter_diet_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diet',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
