# Generated by Django 5.1.6 on 2025-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_diet_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='day1',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
