# Generated by Django 5.1.6 on 2025-04-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_diet_day1'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='day2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='day3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='day4',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='day5',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='day6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='day7',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
