# Generated by Django 5.1.6 on 2025-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_diet_day2_diet_day3_diet_day4_diet_day5_diet_day6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='diet_note',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Instrucciones Extra para la dieta'),
        ),
    ]
