# Generated by Django 5.1.6 on 2025-05-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_diet_diet_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diet_note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Instrucciones Extra para la dieta'),
        ),
    ]
