
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/mediafiles
      - ./backend/static:/app/staticfiles
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
    command: ./wait-for-it.sh db:5432 -- gunicorn DraFitApi.wsgi:application --bind 0.0.0.0:8000 --workers 4
    restart: always
    logging:
      driver: "json-file"

  frontend:
    build:
      context: ./frontend/draAcostaFitPage
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: DraFitDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./backend/static:/app/staticfiles
      - ./backend/media:/app/mediafiles
      - ./backend/config/Nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: "json-file"

volumes:
  postgres_data: