# Generated by Django 5.1.6 on 2025-02-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('weight', models.IntegerField(max_length='Peso')),
                ('height', models.IntegerField(max_length='Estatura')),
                ('objetive', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=30, verbose_name='Whatsapp')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('country', models.CharField(max_length=100, verbose_name='Pais')),
                ('city', models.CharField(max_length=100, verbose_name='Pais')),
                ('medical_history', models.TextField(max_length=500, verbose_name='Historia Clinica')),
            ],
            options={
                'verbose_name': 'Pacientes',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
