# Generated by Django 5.1.6 on 2025-02-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_create_at_patient_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estatura'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Historia Clinica'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='objetive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Whatsapp'),
        ),
    ]
