# Generated by Django 5.1.6 on 2025-04-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_age_patient_diseases_patient_food_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, null=True, verbose_name='Sexo'),
        ),
    ]
