# Generated by Django 5.1.6 on 2025-04-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patient_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
