# Generated by Django 5.1.6 on 2025-05-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patient_dob_alter_patient_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='talla_abdomen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida abdomen'),
        ),
        migrations.AddField(
            model_name='patient',
            name='talla_cadera',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida cadera'),
        ),
        migrations.AddField(
            model_name='patient',
            name='talla_cuello',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida Cuello'),
        ),
        migrations.AddField(
            model_name='patient',
            name='talla_pecho',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida pecho'),
        ),
        migrations.AddField(
            model_name='patient',
            name='talla_pierna',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida pierna'),
        ),
    ]
