# Generated by Django 5.1.6 on 2025-05-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_patient_talla_abdomen_patient_talla_cadera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='talla_abdomen',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='talla_cadera',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='talla_cuello',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='talla_pecho',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='talla_pierna',
        ),
        migrations.AddField(
            model_name='patient',
            name='calf_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida pantorrilla'),
        ),
        migrations.AddField(
            model_name='patient',
            name='chest_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida pecho'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hip_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida cadera'),
        ),
        migrations.AddField(
            model_name='patient',
            name='leg_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida pierna'),
        ),
        migrations.AddField(
            model_name='patient',
            name='neck_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida Cuello'),
        ),
        migrations.AddField(
            model_name='patient',
            name='waist_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida cintura'),
        ),
    ]
