# Generated by Django 5.1.6 on 2025-02-22 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointments_create_at_appointments_is_active_and_more'),
        ('patient', '0005_alter_patient_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confimed', 'Confirmada'), ('canceled', 'Cancelada'), ('finished', 'Finalizada')], default='pendient', max_length=120, null=True),
        ),
    ]
