# Generated by Django 5.1.6 on 2025-02-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointments_date_alter_appointments_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (0, 'Jueves'), (0, 'Vienres'), (0, 'Sabado'), (0, 'Domingo')])),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horario',
            },
        ),
    ]
