# Generated by Django 5.1.6 on 2025-02-28 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_availability_create_at_availability_is_active_and_more'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='status',
        ),
        migrations.AddField(
            model_name='appointments',
            name='confirmation_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='confirmation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='whatsapp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
