# Generated by Django 5.1.6 on 2025-03-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
