# Generated by Django 5.1.6 on 2025-03-05 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_appointments_hour_alter_appointments_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='confirmation_method',
        ),
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confimed', 'Confirmada'), ('canceled', 'Cancelada'), ('finished', 'Finalizada')], default='pending', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='confirmation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
