# Generated by Django 5.1.6 on 2025-03-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_confirmed_appointments_is_confirmed_and_more'),
        ('doctor', '0005_alter_doctoravailability_doctor'),
        ('patient', '0006_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient.patient'),
        ),
    ]
