# Generated by Django 5.1.6 on 2025-03-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_appointments_doctor_alter_appointments_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='reminder_12h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
