# Generated by Django 5.1.6 on 2025-02-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/all-services')),
                ('title_es', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description_es', models.CharField(max_length=100, verbose_name='Descripción')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title')),
                ('description_en', models.CharField(max_length=100, verbose_name='Description')),
                ('text_alt', models.CharField(max_length=100, verbose_name='Texto Alternativo')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Todos los Servicios',
                'verbose_name_plural': 'Todos los servicios',
            },
        ),
        migrations.CreateModel(
            name='BeforeAndAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/before-after')),
                ('Title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('Title_es', models.CharField(max_length=100, verbose_name='Title')),
                ('description_en', models.CharField(max_length=100, verbose_name='Description')),
                ('text_alt', models.CharField(max_length=100, verbose_name='Texto Alternativo')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Introducción Servicios',
                'verbose_name_plural': 'Introducción Servicios',
            },
        ),
        migrations.CreateModel(
            name='DetailPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_es', models.CharField(max_length=100, verbose_name='Titulo')),
                ('detail_en', models.CharField(max_length=100, verbose_name='Title')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Detalles Planes',
                'verbose_name_plural': 'Detalles Planes',
            },
        ),
        migrations.CreateModel(
            name='InfoPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/all-services')),
                ('title_es', models.CharField(max_length=100, verbose_name='Titulo')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title')),
                ('price', models.CharField(max_length=100, verbose_name='Descripción')),
                ('text_alt', models.CharField(max_length=100, verbose_name='Texto Alternativo')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Información Planes',
                'verbose_name_plural': 'Información Planes',
            },
        ),
        migrations.CreateModel(
            name='IntroductionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/introduction-services')),
                ('Title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('Title_es', models.CharField(max_length=100, verbose_name='Title')),
                ('description_en', models.CharField(max_length=100, verbose_name='Description')),
                ('text_alt', models.CharField(max_length=100, verbose_name='Texto Alternativo')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Introducción Servicios',
                'verbose_name_plural': 'Introducción Servicios',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/logo', verbose_name='Logo')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('text_alt', models.CharField(max_length=100, verbose_name='Texto Alternativo')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=100, verbose_name='Nombre Pagina')),
                ('name_en', models.CharField(max_length=100, verbose_name='Page Name')),
                ('url', models.CharField(max_length=150, verbose_name='URL')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Navegación',
                'verbose_name_plural': 'Navegación',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.ImageField(upload_to='media/slider', verbose_name='Slider')),
                ('Title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('Title_es', models.CharField(max_length=100, verbose_name='Title')),
                ('description_en', models.CharField(max_length=100, verbose_name='Description')),
                ('text_alt', models.CharField(max_length=100, verbose_name='Texto Alternativo')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='TestimonyPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_es', models.CharField(max_length=100, verbose_name='Descrition')),
                ('title_es', models.CharField(max_length=100, verbose_name='Title')),
                ('description_en', models.CharField(max_length=100, verbose_name='Description')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Testimonios',
                'verbose_name_plural': 'Testimonios',
            },
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('title_es', models.CharField(max_length=100, verbose_name='Title')),
                ('description_en', models.CharField(max_length=100, verbose_name='Description')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Introducción Servicios',
                'verbose_name_plural': 'Introducción Servicios',
            },
        ),
    ]
