# Generated by Django 5.1.6 on 2025-02-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beforeandafter',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='beforeandafter',
            old_name='Title_es',
            new_name='title_es',
        ),
        migrations.RenameField(
            model_name='introductionservice',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='introductionservice',
            old_name='Title_es',
            new_name='title_es',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='Title_es',
            new_name='title_es',
        ),
        migrations.RenameField(
            model_name='whoweare',
            old_name='Title',
            new_name='title',
        ),
    ]
