# Generated by Django 5.1.6 on 2025-02-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_title_beforeandafter_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introductionservice',
            name='image',
            field=models.ImageField(upload_to='introduction-services'),
        ),
    ]
