# Generated by Django 5.1.6 on 2025-02-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_slider_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beforeandafter',
            options={'verbose_name': 'Antes y Despues', 'verbose_name_plural': 'Antes y Despues'},
        ),
        migrations.AlterModelOptions(
            name='whoweare',
            options={'verbose_name': 'Quienes Somos', 'verbose_name_plural': 'Quienes Somos'},
        ),
        migrations.AddField(
            model_name='testimonypatients',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='allservice',
            name='image',
            field=models.ImageField(upload_to='all-services'),
        ),
        migrations.AlterField(
            model_name='beforeandafter',
            name='image',
            field=models.ImageField(upload_to='before-after'),
        ),
        migrations.AlterField(
            model_name='infoplans',
            name='image',
            field=models.ImageField(upload_to='all-services'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(upload_to='logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='testimonypatients',
            name='description_es',
            field=models.CharField(max_length=100, verbose_name='Descipción'),
        ),
        migrations.AlterField(
            model_name='testimonypatients',
            name='title_es',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
