# Generated by Django 5.1.6 on 2025-02-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_beforeandafter_options_alter_whoweare_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
        migrations.AddField(
            model_name='slider',
            name='description_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Page Name'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
