# Generated by Django 5.1.6 on 2025-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_slider_description_remove_slider_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beforeandafter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='beforeandafter',
            name='title',
        ),
        migrations.RemoveField(
            model_name='introductionservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='introductionservice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='description',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='title',
        ),
        migrations.AddField(
            model_name='beforeandafter',
            name='description_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='beforeandafter',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='introductionservice',
            name='description_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='introductionservice',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='description_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='beforeandafter',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='beforeandafter',
            name='title_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='introductionservice',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='introductionservice',
            name='title_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='title_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
