# Generated by Django 5.1.6 on 2025-02-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_beforeandafter_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allservice',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='allservice',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='detailplans',
            name='detail_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='infoplans',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='infoplans',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='testimonypatients',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
    ]
